# Generated by Django 5.1.4 on 2025-01-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_habitat_bird_lower_elevation_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdset',
            name='audio',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
