# Generated by Django 5.1.4 on 2025-01-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0005_alter_birdset_bird'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdset',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
