# Generated by Django 5.1.4 on 2025-01-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_delete_bird'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=255, unique=True)),
                ('wikipedia_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BirdContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('bird', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='chat.bird')),
            ],
        ),
    ]
