# Generated by Django 5.1.4 on 2025-01-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdcontent',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
