# Generated by Django 5.1.4 on 2025-01-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_birdcontent_embedding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bird',
            new_name='BirdChat',
        ),
    ]
