# Generated by Django 5.1.4 on 2025-01-03 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('birds', '0003_habitat_bird_lower_elevation_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('description', models.TextField(blank=True, null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('place_type', models.CharField(choices=[('Observation Site', 'Observation Site'), ('Monitoring Station', 'Monitoring Station'), ('Protected Area', 'Protected Area'), ('National Park', 'National Park'), ('Forest', 'Forest'), ('Application', 'Application')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BirdLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotted_time', models.DateTimeField()),
                ('bird_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bird_locations', to='birds.bird')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.location')),
            ],
        ),
    ]
