# Generated by Django 5.1.4 on 2025-01-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birdlocation',
            old_name='bird_id',
            new_name='bird',
        ),
    ]
