# Generated by Django 5.1.4 on 2025-01-04 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0005_alter_birdset_bird'),
        ('locations', '0002_rename_bird_id_birdlocation_bird'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='habitat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitat', to='birds.habitat'),
        ),
        migrations.AlterField(
            model_name='birdlocation',
            name='bird',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bird', to='birds.bird'),
        ),
        migrations.AlterField(
            model_name='birdlocation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bird_locations', to='locations.location'),
        ),
    ]
