# Generated by Django 5.1.4 on 2025-01-04 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0006_alter_birdset_audio'),
        ('locations', '0003_location_habitat_alter_birdlocation_bird_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='habitat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='birds.habitat'),
        ),
    ]
